# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='news_time',
            field=models.DateTimeField(verbose_name='新闻源时间'),
        ),
    ]
