# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170724_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='article',
            field=models.TextField(default='', verbose_name='文章'),
        ),
    ]
