# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsinfo_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='author',
            field=models.CharField(default='', max_length=64, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='origin',
            field=models.CharField(default='', max_length=32, verbose_name='来源'),
        ),
    ]
