# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_attention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='标题')),
                ('abstract', models.CharField(default='', max_length=255, verbose_name='摘要')),
                ('first_img', models.CharField(default='', max_length=255, verbose_name='首图')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('area', models.CharField(default='', max_length=255, verbose_name='地点')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Jh_User')),
            ],
            options={
                'db_table': 'commentary_blog',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Jh_User')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentary.Blog')),
            ],
            options={
                'db_table': 'commentary_blog_comment',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消点赞')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Jh_User')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentary.Blog')),
            ],
            options={
                'db_table': 'commentary_blog_likes',
            },
        ),
    ]
