# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='abstract',
            field=models.TextField(default='', verbose_name='摘要'),
        ),
    ]
