# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_attention'),
        ('commentary', '0002_auto_20170908_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消点赞')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Jh_User')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentary.BlogComment')),
            ],
            options={
                'db_table': 'commentary_comment_likes',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='parent_blog_id',
            field=models.IntegerField(default=0, verbose_name='转发源短评id'),
        ),
    ]
