# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_attention'),
        ('commentary', '0003_auto_20170911_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(default='', max_length=16, verbose_name='消息类型')),
                ('content', models.TextField(default='', verbose_name='消息内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='account.Jh_User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='account.Jh_User')),
            ],
            options={
                'db_table': 'commentary_notice',
            },
        ),
    ]
