# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_wineinfo_year'),
        ('commentary', '0004_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentary.Blog')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.WineInfo')),
            ],
            options={
                'db_table': 'commentary_wine_blog',
            },
        ),
    ]
