# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20170627_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wineinfo',
            name='proposed_price',
            field=models.FloatField(verbose_name='初始价格'),
        ),
        migrations.AlterModelTable(
            name='commission',
            table='wine_commission',
        ),
        migrations.AlterModelTable(
            name='deal',
            table='wine_deal',
        ),
        migrations.AlterModelTable(
            name='position',
            table='wine_position',
        ),
    ]
