# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20170727_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='wineinfo',
            name='name_en',
            field=models.CharField(default='', max_length=128, verbose_name='英文名称'),
        ),
    ]
