# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_wineinfo_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='wineinfo',
            name='year',
            field=models.CharField(default='', max_length=4, verbose_name='年份'),
        ),
    ]
