# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jh_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=16, null=True, verbose_name='用户id')),
                ('nickname', models.CharField(max_length=40, null=True, verbose_name='昵称')),
                ('mobile', models.CharField(default='', max_length=12, verbose_name='手机号码')),
                ('img_url', models.CharField(default='', max_length=255, verbose_name='头像url')),
                ('email', models.CharField(default='', max_length=64, verbose_name='邮箱')),
                ('role', models.IntegerField(choices=[(0, '普通用户'), (1, '管理人员')], default=0, verbose_name='用户权限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否无效用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_jh_user',
            },
        ),
    ]
