# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jh_user',
            name='userid',
        ),
        migrations.AddField(
            model_name='jh_user',
            name='union_id',
            field=models.CharField(max_length=16, null=True, verbose_name='用户union_id'),
        ),
    ]
