# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170621_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='jh_user',
            name='personal_select',
            field=models.CharField(default='', max_length=500, verbose_name='自选'),
        ),
        migrations.AddField(
            model_name='jh_user',
            name='trade_passwd',
            field=models.CharField(default='', max_length=16, verbose_name='交易密码'),
        ),
    ]
