# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170623_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='jh_user',
            name='funds',
            field=models.FloatField(default=0, verbose_name='资金'),
        ),
        migrations.AlterField(
            model_name='jh_user',
            name='trade_passwd',
            field=models.CharField(default='', max_length=64, verbose_name='交易密码'),
        ),
    ]
