# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170627_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jh_user',
            name='union_id',
            field=models.CharField(max_length=128, null=True, verbose_name='用户union_id'),
        ),
    ]
