# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170725_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_obj_type', models.IntegerField(choices=[(0, '用户'), (1, '酒')], default=0, verbose_name='关注对象类型')),
                ('attention_obj_id', models.CharField(default='', max_length=8, verbose_name='关注对象id')),
                ('attention_obj_name', models.CharField(default='', max_length=40, verbose_name='关注对象名称')),
                ('is_attention', models.BooleanField(default=False, verbose_name='是否关注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Jh_User')),
            ],
            options={
                'db_table': 'account_attention',
            },
        ),
    ]
