# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.CharField(max_length=13, verbose_name='时间戳'),
        ),
    ]
