# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170711_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_img_url',
            field=models.CharField(default='', max_length=255, verbose_name='视频截图'),
        ),
    ]
